spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    #发送确认 对应RabbitTemplate.ConfirmCallback接口
    publisher-confirms: true
    #发送失败回退，对应RabbitTemplate.ReturnCallback接口
    publisher-returns: true
    #手动提交ack
    listener:
      direct:
        acknowledge-mode: manual
      simple:
        acknowledge-mode: manual